name: Get Appointments and Update ICS

on:
  schedule:
    - cron: '0/5 * * * *'  # every 10min
  workflow_dispatch:      # allows manual runs if needed

permissions:
  contents: write 

jobs:
  scrape-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get appointments and generate files
        run: |
          python get_buergerbuero_appointments.py
          python generate_ics.py

        # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: Update ICS [skip ci]" || echo "No changes to commit"
          git pull --rebase
          git push
